### ISSUE TITLE
Running Julia on Niagara

### ISSUE THREAD

**Issue by arnavs** [ubcecon/cluster_tools#8]
Vadim is emailing them to figure this out. Opening this issue to remind me to ask him what they say, so we can add it to the repo. 

(Niagara is a different setup, but might as well record the information.)

**Comment by wupeifan** [comment]
What exactly is the problem? Just tried... Not so different from other ones like cedar/beluga.

**Comment by arnavs** [comment]
What Vadim had said was this: 

> I believe that this is because on Niagara, $HOME files are read-only on compute nodes, but Julia compiles packages in a folder in $HOME. Do you know how I can avoid this problem?

> No worries if you haven’t dealt with the Niagara cluster, I’ll contact Compute Canada to see what they say. Niagara is different from other their systems.

But he ended up not contacting them about this, because he got it working on Graham. 

So may as well close.

**Comment by wupeifan** [comment]
Well, probably because he should 1) either use the system provided Julia 2) install things under some directories other than $HOME. I think cedar also has a similar issue (but that's good -- people shouldn't install things under $HOME while running stuff on the compute nodes)
